### PR TITLE
Remove duplicate tests introduced by #386

### PR DESCRIPTION
**Pull request by smheidrich**
Maybe there's something here that I'm not getting, so please correct me if I'm wrong, but to me it seems like #386 introduced a ton of duplicate tests in ``test_local.py``; not in the sense of "there are already similar tests for the same thing", but *verbatim*, byte-for-byte copies.

You can see this for yourself by running ``pyflakes`` on the file in question:

-----

<details><summary><code>pyflakes</code> output</summary>

``` console
$ git describe
v1.6.7-13-gb1ac118
$ pyflakes test_local.py 
test_local.py:15: 'plumbum._testtools.xfail_on_pypy' imported but unused
test_local.py:291: 'plumbum.cmd.non_exist1N9' imported but unused
test_local.py:403: 'plumbum.cmd.cat' imported but unused
test_local.py:403: 'plumbum.cmd.head' imported but unused
test_local.py:564: 'plumbum.cmd.cat' imported but unused
test_local.py:576: 'plumbum.cmd.cat' imported but unused
test_local.py:770: redefinition of unused 'test_contains' from line 343
test_local.py:796: redefinition of unused 'test_redirection' from line 420
test_local.py:820: redefinition of unused 'test_popen' from line 444
test_local.py:829: redefinition of unused 'test_run' from line 453
test_local.py:835: redefinition of unused 'test_timeout' from line 459
test_local.py:840: redefinition of unused 'test_pipe_stderr' from line 464
test_local.py:851: redefinition of unused 'test_fair_error_attribution' from line 475
test_local.py:861: redefinition of unused 'test_iter_lines_timeout' from line 485
test_local.py:873: redefinition of unused 'test_iter_lines_error' from line 497
test_local.py:883: redefinition of unused 'test_modifiers' from line 507
test_local.py:898: redefinition of unused 'test_tee_modifier' from line 522
test_local.py:908: redefinition of unused 'test_arg_expansion' from line 532
test_local.py:914: redefinition of unused 'test_session' from line 538
test_local.py:926: redefinition of unused 'test_quoting' from line 550
test_local.py:939: redefinition of unused 'test_tempdir' from line 563
test_local.py:940: 'plumbum.cmd.cat' imported but unused
test_local.py:951: redefinition of unused 'test_direct_open_tmpdir' from line 575
test_local.py:952: 'plumbum.cmd.cat' imported but unused
test_local.py:964: redefinition of unused 'test_read_write_str' from line 588
test_local.py:970: redefinition of unused 'test_read_write_unicode' from line 594
test_local.py:976: redefinition of unused 'test_read_write_bin' from line 600
test_local.py:982: redefinition of unused 'test_links' from line 606
test_local.py:994: redefinition of unused 'test_list_processes' from line 618
test_local.py:997: redefinition of unused 'test_pgrep' from line 621
test_local.py:1000: redefinition of unused '_generate_sigint' from line 624
test_local.py:1009: redefinition of unused 'test_same_sesion' from line 633
test_local.py:1019: redefinition of unused 'test_new_session' from line 643
test_local.py:1029: redefinition of unused 'test_local_daemon' from line 653
test_local.py:1036: redefinition of unused 'test_atomic_file' from line 660
test_local.py:1046: redefinition of unused 'test_atomic_file2' from line 670
test_local.py:1065: redefinition of unused 'test_pid_file' from line 689
test_local.py:1081: redefinition of unused 'test_atomic_counter' from line 705
test_local.py:1111: redefinition of unused 'test_atomic_counter2' from line 735
test_local.py:1129: redefinition of unused 'test_bound_env' from line 753
test_local.py:1141: redefinition of unused 'test_nesting_lists_as_argv' from line 765
test_local.py:1146: redefinition of unused 'test_contains' from line 770
test_local.py:1149: redefinition of unused 'test_issue_139' from line 773
test_local.py:1152: redefinition of unused 'test_pipeline_failure' from line 776
test_local.py:1157: redefinition of unused 'test_pipeline_retcode' from line 781
test_local.py:1165: redefinition of unused 'test_pipeline_stdin' from line 789
```

</details>

-----

This PR aims to remove these. I went through them one-by-one to make sure they are actually identical to the originals, and the only changes I found were irrelevant things like whitespaces. So I hope this should be fine.

### CODE REVIEW

**Comment by henryiii** [comment]
Thanks!

**Comment by smheidrich** [comment]
Thanks for merging! :+1:
